config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  resources :listings do
    resources :reviews, except: [:show, :index]  
   end

  resources :order_items
  resource :cart, only: [:show, :thank_you] 

  resources :messages do
    resources :comments
  end
  
   post '/search' => 'listings#search'  #added for search
  
  root 'listings#index'

  get 'shop' => "listings#shop"
  get 'seller' => "listings#seller"
  post 'cart/thank-you' => "carts#thank_you"

end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :user
	has_many :comments
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]	
	before_action :find_message, only: [:show, :edit, :update, :destroy]

	def index
		@messages = Message.all.order("created_at DESC")
	end

	def show
	end

	def new 
		@message = current_user.messages.build
	end

	def create
		@message = current_user.messages.build(message_params)
		if @message.save
			redirect_to messages_path
		else
			render 'new'
		end
	end

	def edit

	end

	def update
		if @message.update(message_params)
			redirect_to message_path
		else
			render 'edit'
		end
	end

	def destroy
		@message.destroy
		redirect_to messages_path
	end 

	private

	def message_params
		params.require(:message).permit(:title, :description)
	end

	def find_message
		@message = Message.find(params[:id])
	end
end

app/views/messages/_forms.html.erb
<%= form_for @message do |f| %>
  	<div class="form-group">
		<%= f.label "Message Title" %>
		<%= f.text_field  :title, id: :message_title, class:"form-control" %>
  	</div>
    <div class="form-group">
		<%= f.label "Description" %>
		<%= f.text_field  :description, id: :message_description, class:"form-control" %>
	</div>
	<div class="actions" style="margin-bottom:190px">
		<%= f.button :submit, class:"btn btn-primary" %>
	</div>
<% end %>

app/views/messages/edit.html.erb
<h1>Edit Message</h1>

<%= render 'forms' %>

app/views/messages/index.html.erb
<h1>Message Board</h1>
<div class="row">
<% @messages.each do |m| %>
	<div class="col-lg-4 col-md-6">
		<div class="message">
			<h2 class="message-title"><%= m.title %></h2>
			<%= link_to 'view message', message_path(m), class:"btn-custom float-right" %>
		</div>
	</div>
<% end %>
</div>
<p><%= link_to 'New Message', new_message_path, class:"btn btn-link" %></p>

app/views/messages/new.html.erb
<div class="col-md-8 offset-2">
	<h1>New Message</h1>

	<%= render 'forms' %>
</div>

app/views/messages/show.html.erb
<div class="col-md-8 offset-2">
	<div class="message-show">
		<h2><%= @message.title %></h2>
		<p class="message-posted-by">Posted by: <%= @message.user.email %> <%= time_ago_in_words(@message.created_at) %> ago</p>
		<p class="message-desc"><%= @message.description %></h2>

		<h3>Comments:</h3>
		<%= render @message.comments %>

		<h3 class="reply-to-msg">Reply to Message</h3>
		<%= render 'comments/form'%>

		<div class="links btn-group">
			<p><%= link_to "Back", messages_path, class:"btn btn-light" %> 
			<% if user_signed_in? %>
				<% if @message.user_id == current_user.id || current_user.admin? %>
					<%= link_to "Edit", edit_message_path, class:"btn btn-light"  %> 
					<%= link_to "Delete", message_path(@message), class:"btn btn-light", method: :delete, data: {confirm: 'Are you sure'} %></p>
				<% end %>
			<% end %>
		</div>
	</div>
</div>
<br/>