config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  resources :listings do
    resources :reviews, except: [:show, :index]  
   end

  resources :order_items
  resource :cart, only: [:show, :thank_you] 

  resources :messages do
    resources :comments
  end
  
   post '/search' => 'listings#search'  #added for search
  
  root 'listings#index'

  get 'shop' => "listings#shop"
  get 'seller' => "listings#seller"
  post 'cart/thank-you' => "carts#thank_you"

end

app/models/listing.rb
class Listing < ApplicationRecord
	has_attached_file :image, styles: { medium: "200x200>", thumb: "100x100>" }, default_url: "default.jpg"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

	validates_associated :category
	validates :category, :title, :artist, :description, :price, presence: true
	validates :price, numericality: {greater_than: 0}

	belongs_to :user
	belongs_to :category
	has_many :reviews, dependent: :destroy
	has_many :order_items
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:seller, :new, :create, :edit, :update, :destroy]
  before_action :categories, only: [:shop, :edit, :new, :create]


  def seller
    if current_user.admin?
      @listings = Listing.all.order("created_at DESC")
    else
      @listings = Listing.where(user: current_user).order("created_at DESC")
    end
  end

  # GET /listings
  def shop
    if params[:category].blank?
      @listings = Listing.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @listings = Listing.where(:category_id => @category_id).order("created_at DESC")
    end 
  end

  # GET /listings
  def index
    @history = OrderItem.all.where(buyer_id: current_user).order("created_at DESC")
    @listings = Listing.limit(4).order("created_at DESC")   
    @orders = Order.all.where(buyer: current_user).order("created_at DESC")    
  end

  # GET /listings/1
  def show
     @order_item = current_order.order_items.new
     @listings = Listing.all
     @reviews = Review.where(listing_id: @listing.id).order("created_at DESC")
       if @reviews.blank?
        @avg_rating = 0
      else
        @avg_rating = @reviews.average(:rating).round(2)
      end 
  end
 
  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id
    @listing.category_id = params[:category_id]

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /listings/1
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /listings/1
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
    end
  end

def search
  #@search_term = params[:q]
  st = "%#{params[:q]}%"
  @listings = Listing.where("title like ?", st)
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
		params.require(:listing).permit(:title, :artist, :description, :price, :image, :user_id, :category_id)
    end

    def categories
      @categories = Category.all.map{ |c| [c.name, c.id] }
    end
end






 

app/views/listings/_category.html.erb
<div class="category">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to "Add New Item", new_listing_path, class:"btn-link" %></li>
        <% end %>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu  centre" role="menu">
	          <%= link_to 'all', shop_path, class:"btn-link" %>
            <% Category.all.each do |category| %>
              <li class="<%= 'active' if params[:category] == category.name %>">
                <%= link_to category.name, shop_path(category: category.name), class:"btn-link" %>
              </li>
            <% end %>
          </ul>
        </li> 
      </ul>
</div>

app/views/listings/_edit-form.html.erb
<%= form_with(model: listing,  local: true, :html => { :multipart => true }) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>     
      <h4><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h4>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
  	<%= form.label :category %><br/>
    <%= form.select :category_id, @categories %>
  </div>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :listing_title, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :artist %>
    <%= form.text_field :artist, id: :listing_artist, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, id: :listing_description, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, id: :listing_price, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, id: :listing_image, class:"form-control"  %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/listings/_form.html.erb
<%= form_with(model: listing,  local: true, :html => { :multipart => true }) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
  </button>
      <h4><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h4>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="form-group">
    <%= form.label :category %><br/>
    <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category") %>
  </div> 

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :listing_title, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :artist %>
    <%= form.text_field :artist, id: :listing_artist, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, id: :listing_description, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, id: :listing_price, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, id: :listing_image, class:"form-control"  %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/listings/_mailchimp.html.erb
<!-- Begin MailChimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/horizontal-slim-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
  #mc_embed_signup{clear:left; font:14px Helvetica,Arial,sans-serif; width:100%;}
  /* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
     We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="https://simplyweb.us11.list-manage.com/subscribe/post?u=b9f90fed04eb959c80da6ad34&amp;id=9b89fb4a4a" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
  <label for="mce-EMAIL">Subscribe for our newsletter</label>
  <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_b9f90fed04eb959c80da6ad34_9b89fb4a4a" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div><br/><br/>
</form>
</div>

<!--End mc_embed_signup-->

app/views/listings/_purchase-history.html.erb
<% if user_signed_in? %>     

	<!-- Button trigger modal -->
	<button type="button" class="btn btn-danger btn-lg" data-toggle="modal" data-target="#exampleModalCenter">
	  Purchase History
	</button>

	<!-- Modal -->
	<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
	  <div class="modal-dialog modal-dialog-centered" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h5 class="modal-title" id="exampleModalLongTitle"><%= "#{current_user.first_name} #{current_user.last_name}"%> - Purchase History</h5>
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	          <span aria-hidden="true">&times;</span>
	        </button>
	      </div>
	      <div class="modal-body">
				<table class="table table-bordered table-striped">
				  <tr class="centre">
				    <th>Image</th>
				    <th>Item</th>
				    <th>Price</th>
				    <th>Seller</th>
				    <th>Date Purchased</th>   
				    <th>Write a Review</th> 
				  </tr>

				  <% @orders.each do |order| %>    
					  <tr class="centre">
					    <td></td>
					    <td></td>
					    <td></td>
					    <td></td>
					    <td></td>
					    <td><%=link_to 'review', '#', class:"btn btn-primary" %></td>
					  </tr>
				  <% end %>
				</table>
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
	      </div>
	    </div>
	  </div>
	</div>
<% end %>

app/views/listings/_purchases.html.erb
<% if user_signed_in? %>     

	<!-- Button trigger modal -->
	<button type="button" class="btn btn-danger btn-lg" data-toggle="modal" data-target="#exampleModalCenter">
	  Purchase History
	</button>

	<!-- Modal -->
	<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
	  <div class="modal-dialog modal-dialog-centered" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h5 class="modal-title" id="exampleModalLongTitle"><%= "#{current_user.first_name} #{current_user.last_name}"%> - Purchase History</h5>
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	          <span aria-hidden="true">&times;</span>
	        </button>
	      </div>

	      <div class="modal-body">
	      	<table class="table table-bordered">
						<tr class="centre">
							<thead class="thead-light">
							  <th>Image</th>
							  <th>Item</th>
							  <th>Price</th>
							</thead>
						</tr>
						<% @history.each do |item| %>
							<div class="row">
							<tr class="centre">
								<td><%= image_tag item.listing.image.url(:thumb) %></td>
								<td style="padding-left: 20px;"><h3><%= item.listing.title %></h3>	
								<td><%= number_to_currency(item.listing.price, :locale => :ir) %></td>
							</tr>
							</div>
						<% end %>
					</table>
	      </div>

	      <div class="modal-footer">
	        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
	      </div>
	    </div>
	  </div>
	</div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'edit-form', listing: @listing %>

<%= link_to 'Shop', @listing, class:"btn btn-link" %> |
<%= link_to 'Back', listings_path, class:"btn btn-link" %>
<br/>

app/views/listings/index.html.erb
<div class="jumbotron jumbotron-fluid shadow">
</div>

<div class="centre"><%= render 'listings/purchases'%>
  <%= link_to "Shop Now", shop_path, class:"btn btn-danger btn-lg"  %></div><br/>

<%= render 'listings/mailchimp'%>
<br>
			<!-- front content -->
 <div class="centre">
  <div class="row">
    <% @listings.each do |listing| %>    
      <div class="col-lg col-md">
	      
				<div class="flip-container" ontouchstart="this.classList.toggle('hover');">
					<div class="flipper">
						<div class="front">	      
	      
							<div class="img-thumbnail">
							<%= link_to image_tag(listing.image.url(:medium)), listing, class:"img-fluid img-med" %>
								<div class="caption">
									<h3><%= listing.title %></h3>
									<p>Artist: <%= listing.artist %></p>
									<p>Type: <%= listing.category.name %></p>   
									<p><%= number_to_currency(listing.price, :locale => :ir) %></p>
									<p><%="Sold by: #{listing.user.first_name} #{listing.user.last_name}"%></p>
          			</div>  <!-- end caption -->
             	</div> <!-- end thumbnail -->
  					</div> <!-- end front -->
  					
						<div class="back centre">
							<h3>Description</h3>
							<span style="center">*****</span>
							<p><%= listing.description %></p>
							<span style="center">*****</span>
						</div>
						
					</div>  <!-- end flipper -->
				</div>  <!-- end flip container -->        
     </div> <!-- end col -->
    <% end %>  <!-- end loop -->
  </div> <!-- end row -->
</div> <!-- end centre -->
<br/>

<% if user_signed_in? %>
  <p><%= link_to 'New Listing', new_listing_path, class:"btn btn-link" %></p>
<% end %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path, class:"btn btn-link"  %>

app/views/listings/search.html.erb
<% if @listings.length ==0 %>
no results were found 
<% end %>

<br/>
<div class="centre">
  <div class="row">
<% @listings.each do |listing| %>    
      <div class="col-md-3">
        <div class="img-thumbnail">
          <%= link_to image_tag(listing.image.url(:medium)), listing, class:"img-fluid" %>
          <div class="caption">
            <h3><%= listing.title %></h3>
            <p>Artist: <%= listing.artist %></p>
            <p>Type: <%= listing.category.name %></p>   
            <p><%= number_to_currency(listing.price, :locale => :ir) %></p>
            <p><%="Sold by: #{listing.user.first_name} #{listing.user.last_name}"%></p>
         </div>
        </div>
     </div>
    <% end %>
  </div>
</div>

app/views/listings/seller.html.erb
<table class="table table-bordered table-striped">
  <tr class="centre">
    <th>Image</th>
    <th>Name</th>
    <th>Description</th>
    <th>Price</th>
    <th>Action</th>    
  </tr>
  <% @listings.each do |listing| %>    
	  <tr>
	    <td><%= image_tag listing.image.url(:thumb), class:"manage-img" %></td>
	    <td><%="#{listing.user.first_name} #{listing.user.last_name}"%></td>
	    <td><%= listing.description %></td>
	    <td><%= number_to_currency(listing.price, :locale => :ir) %></td>
	    <td>
	      <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Action</button>
	      <div class="dropdown-menu centre">
	        <%= link_to "View", listing, class:"centre" %><br/>
	        <%= link_to "Edit", edit_listing_path(listing), class:"centre" %><br/>
	        <%= link_to "Destroy", listing, class:"centre", method: :delete, data: { confirm: 'Are you sure?' } %>
	      </div>
	    </td>
	  </tr>
  <% end %>
</table>

<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class:"btn btn-primary custom_btn" %>
<% end %>
<br/>

app/views/listings/shop.html.erb
<%= render 'listings/category' %>

<h1 class="current-category"><%= params[:category]%></h1>

<%if @listings == 0 %>
  <h1>There are no items currently available for this category</h1>
<% end %>

<div class="centre">
  <div class="row">
    <% @listings.each do | listing | %>    
      <div class="col-md custom-thumb">
        <div class="img-thumbnail">
          <%= link_to image_tag(listing.image.url(:medium)), listing, class:"img-fluid" %>
          <div class="caption">
            <h3><%= listing.title %></h3>
            <p>Artist: <%= listing.artist %></p>
            <p>Type: <%= listing.category.name %></p>   
            <p><%= number_to_currency(listing.price, :locale => :ir) %></p>
            <p><%="Sold by: #{listing.user.first_name} #{listing.user.last_name}"%></p>
         </div>
        </div>
     </div>
    <% end %>
  </div>
</div>

app/views/listings/show.html.erb
<div class="row">
  <div class="col-md-6 col-lg-3">
    <div class="img-thumbnail custom-thumb">
      <%= image_tag @listing.image.url(:medium), class:"img-fluid, centre_img" %>
    </div>
		
    <p class="star-rating" data-score= <%= @avg_rating %>></p>
    <p><%= "#{@reviews.length} reviews" %></p>

    <% if user_signed_in? %>     
    	<p><%= link_to "Write a Review", new_listing_review_path(@listing), class:"btn btn-primary" %></p>
			<% if (@listing.user == current_user) || (current_user.admin?) %>   
      	<%= link_to 'Edit', edit_listing_path(@listing), class:"btn btn-link"  %> |
			<% end %>  
    <% end %>
    
    <%= link_to 'Back', shop_path, class:"btn btn-link"  %>
  </div>

  <div class="col-md-6 col-lg-9">
    <h3><%= @listing.title %></h3>
    <p>Artist: <%= @listing.artist %></p>
    <p>Type: <%= @listing.category.name %></p>
    <p>Description:<br/> <%= @listing.description %></p>

        <%= form_for(@order_item, remote: true) do |f| %>
        <%= f.hidden_field :listing_id, value: @listing.id %>
        <%= f.hidden_field :seller_id, value: @listing.user_id %>
        <%= f.hidden_field :buyer_id, value: current_user.id %>        
        <p>Price: <%= number_to_currency(@listing.price, :locale => :ir) %></p>
        <div class="form-group">
          <p>Quantity: <%= f.number_field :quantity, value: 1, min: 1 %></p>
        </div>
        <% if user_signed_in? %>
          <p><%= f.submit "Add to cart", class: 'btn btn-primary' %></p>
        <% else %>
          <h3 style="color:red;">To add this item to the cart you must first be logged in</h3>
          <p><%= link_to "Log In", user_session_path, class: 'btn btn-primary' %></p>

        <% end %>
      <% end %>

<br/>
    <% if @reviews.blank? %>
      <h3>No reviews yet! Be the first to write one.</h3>
    <% else %>
    <h3>Current Reviews</h3>
    <table class="table">
      <tbody>
        <% @reviews.each do | review | %>  
          <tr>
            <td><h4><%= "#{review.user.first_name.capitalize} #{review.user.last_name.capitalize[0]}."%></h4>
              <p><%= review.created_at.strftime("%d/%m/%y") %></p>
            </td>
            <td>
              <div class="star-rating" data-score= <%= review.rating %> ></div><br/>
              <p><%= h(review.comment).gsub(/\n/, '<br/>').html_safe %></p>   
              
              <% if user_signed_in? %>     
                <% if (review.user == current_user) || (current_user.admin?) %>    
                  <%= link_to "Edit", edit_listing_review_path(@listing, review), class:"btn btn-link"  %> |
                  <%= link_to "Delete", listing_review_path(@listing, review), class:"btn btn-link" , method: :delete %>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <% end %>
  </div>
</div>
</div>

<script>
  $('.star-rating').raty({
    path: 'https://s3-eu-west-1.amazonaws.com/good-vibrations/images/',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>