config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  resources :listings do
    resources :reviews, except: [:show, :index]  
   end

  resources :order_items
  resource :cart, only: [:show, :thank_you] 

  resources :messages do
    resources :comments
  end
  
   post '/search' => 'listings#search'  #added for search
  
  root 'listings#index'

  get 'shop' => "listings#shop"
  get 'seller' => "listings#seller"
  post 'cart/thank-you' => "carts#thank_you"

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :message
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!	
	before_action :find_message
	before_action :find_comment, except: [:create]

	def create
		@comment = @message.comments.create(comment_params)
		@comment.user_id = current_user.id

		if @comment.save
			redirect_to message_path(@message)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @comment.update(comment_params)
			redirect_to message_path(@message)
		else
			render 'edit'
		end
	end

	def destroy
		@comment.destroy
		redirect_to message_path(@message)
	end

	private

	def comment_params
		params.require(:comment).permit(:content)
	end

	def find_message
		@message = Message.find(params[:message_id])
	end

	def find_comment
		@comment = @message.comments.find(params[:id])		
	end

end

app/views/comments/_comment.html.erb
<div class="comment">
	<p class="comment-content"><%= comment.content %></p>
	<p class="comment-posted-by">Posted by: <%= comment.user.email %> <%= time_ago_in_words(comment.created_at) %> ago</p>

	<div class="links">
		<% if user_signed_in? %>
			<% if comment.user_id == current_user.id || current_user.admin? %>
				<%= link_to 'Edit', edit_message_comment_path(comment.message, comment), class:"btn btn-link" %>|
				<%= link_to 'Delete', message_comment_path(comment.message, comment), class:"btn btn-link", method: :delete, data: { confirm: "Are you sure?"}%>
			<% end %>
		<% end %>
	</div>
</div>

app/views/comments/_form.html.erb
<%= form_for ([@message, @message.comments.build]) do |f| %>
	<div class="form-group">
		<%= f.label "Comment" %>
		<%= f.text_field  :content, id: :comments_content, class:"form-control" %>
	</div>
  <div class="actions">	
		<%= f.button :submit, class:"btn-custom"%>
	</div>
<%end%>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= form_for ([@message, @comment]) do | f |%>
  <div class="form-group">
		<%= f.text_field :content, label: "Comment", class:"form-control" %>
		<%= f.submit class:"btn btn-primary" %>
	</div>
<% end %>