config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  resources :listings do
    resources :reviews, except: [:show, :index]  
   end

  resources :order_items
  resource :cart, only: [:show, :thank_you] 

  resources :messages do
    resources :comments
  end
  
   post '/search' => 'listings#search'  #added for search
  
  root 'listings#index'

  get 'shop' => "listings#shop"
  get 'seller' => "listings#seller"
  post 'cart/thank-you' => "carts#thank_you"

end

app/views/layouts/_bootstrap.html.erb
<!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

app/views/layouts/_cart.html.erb
<%= link_to "#{current_order.order_items.size} items in cart and price #{number_to_currency(current_order.subtotal, :locale => :ir)}", cart_path %>

app/views/layouts/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="https://s3-eu-west-1.amazonaws.com/good-vibrations/images/favicon/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="https://s3-eu-west-1.amazonaws.com/good-vibrations/images/favicon/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="https://s3-eu-west-1.amazonaws.com/good-vibrations/images/favicon/favicon-16x16.png">
<link rel="manifest" href="https://s3-eu-west-1.amazonaws.com/good-vibrations/images/favicon/site.webmanifest">
<link rel="mask-icon" href="https://s3-eu-west-1.amazonaws.com/good-vibrations/images/favicon/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">

app/views/layouts/_footer.html.erb
<div id="footer">
	<%= image_tag 'foursides_logo.jpg' %> &copy; 2018 foursides 
<div class="social-media-footer">
	<%= render 'layouts/social-media' %>
	
	<%= render 'layouts/search' %>
	
	
</div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light">
  <a class="navbar-brand" href="/"><em>Good Vibrations</em></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

   <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <%= render 'layouts/search' %>
      
       <!-- <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> -->       
    </ul>
    <ul class="navbar-nav navbar-right">
        <li class="active cart"><%= render 'layouts/cart' %></li>
        <li><%= link_to image_tag('cart-logo.png'), cart_path, :alt => "cart-logo" %></li>
      
        <% if user_signed_in? %> 
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= "#{current_user.first_name} #{current_user.last_name}"%></a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "Manage Listings", seller_path, class:"nav-link centre" %>                
                <%= link_to "Messages", messages_path, class:"nav-link centre" %>
                <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link centre" %>
                <%= link_to "Sign Out", destroy_user_session_path, class:"nav-link centre", method: :delete %>
              </div>
          </li>

        <% else %>      
          <li><%= link_to "New Profile", new_user_registration_path, class:"nav-link" %></li>
          <li><%= link_to "Sign In", new_user_session_path, class:"nav-link" %></li>
       <% end %> 

    </ul>
  </div>
</nav>

app/views/layouts/_search.html.erb
<%= form_tag("/search", :method => "post") do %>
<%#= label_tag(:q, "Search for:") %>
<%= text_field_tag(:q) %>
<%= submit_tag("Search") %><% end %>

app/views/layouts/_social-media.html.erb
<span data-toggle="tooltip" data-placement="top" title="Facebook">
	<%= link_to image_tag('facebook-ft.png'), 'https://www.facebook.com/good.vibrations.712', :alt => "facebook" %>
</span>
<span data-toggle="tooltip" data-placement="top" title="Twitter">
	<%= link_to image_tag('twitter-ft.png'), 'https://twitter.com/GoodVibrationsD', :alt => "twitter" %>
</span>
<span data-toggle="tooltip" data-placement="top" title="Pinterest">
	<%= link_to image_tag('pinterest-ft.png'), '#', :alt => "pinterest" %>
</span>


<script>

	$(function () {
  		$('[data-toggle="tooltip"]').tooltip()
	});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
  <title>GoodVibrations</title>
      <%= render 'layouts/favicon' %>

      <%= render 'layouts/bootstrap' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= tag :meta, :name => "stripe-key", :content => ENV["STRIPE_PUBLISHABLE_KEY"] %>
    <script src="https://js.stripe.com/v2/"></script>
		<link href="https://fonts.googleapis.com/css?family=Monoton" rel="stylesheet">

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
   
  </head>

  <body>

    <%= render 'layouts/navbar' %>

    <div class="container">
      
      <% flash.each do |name, msg| %>
        <% if msg.is_a?(String) %>
          <div class="alert alert-<%= name=="notice" ? "success" : "danger" %> alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span><span 
              class="sr-only">Close</span></button>
            <%= content_tag :div, msg, :id => "flash_#{name}"%>
          </div>
        <% end %>
      <% end %> 
    
    <%= yield %>
    </div>
    
  </body>
  <footer> 
    <%= render 'layouts/footer' %>
  </footer>
</html>